version: "3.7"

services:
  gateway:
    build:
      context: ./gateway/docker/development/nginx
    ports:
      - "8080:8080"

  php-fpm:
    build:
      context: ./api/.docker/php-fpm
      args:
        PHP_VERSION: 8
        XDEBUG_VERSION: 3.0.1
    user: "$_UID:$_GID"
    volumes:
      - "./api:/application"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  php-cli:
    build:
      context: ./api/.docker/php-cli
      args:
        PHP_VERSION: 8
        XDEBUG_VERSION: 3.0.1
    user: "$_UID:$_GID"
    volumes:
      - "./api:/application"
    links:
      - postgres
    depends_on:
      - postgres

  api:
    build:
      context: ./api/.docker/nginx
    volumes:
      - "./api:/application"

  postgres:
    image: "postgres:12-alpine"
    environment:
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_DB=$POSTGRES_DB"
    ports:
      - "5432:5432"
    volumes:
      - api-postgres:/var/lib/postgresql/data

volumes:
  api-postgres:
