version: "3.0"
services:
  php-fpm:
    build:
      context: ./.docker/php-fpm
      args:
        PHP_VERSION: 8
        XDEBUG_VERSION: 3.0.1
    env_file: .env
    user: "$_UID:$_GID"
    volumes:
      - "./:/application"
    working_dir: "/application"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PHP_IDE_CONFIG: "serverName=docker"

  php-cli:
    build:
      context: ./.docker/php-cli
      args:
        PHP_VERSION: 8
    env_file: .env
    user: "$_UID:$_GID"
    volumes:
      - "$COMPOSER_HOME:$COMPOSER_HOME"
      - "$COMPOSER_CACHE_DIR:$COMPOSER_CACHE_DIR"
      - "./:/application"
    working_dir: "/application"
    links:
      - postgres
    depends_on:
      - postgres

  nginx:
    image: "nginx:1.19.3-alpine"
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - "./:/application"
      - "./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "php-fpm"

  postgres:
    image: "postgres:12-alpine"
    env_file: .env
    environment:
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_DB=$POSTGRES_DB"
    ports:
      - "5432:5432"
    volumes:
      - ./var/postgres-data:/var/lib/postgresql/data
